# Generated by Django 4.0.5 on 2022-06-22 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Added',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'added',
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('amount', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=30)),
            ],
            options={
                'db_table': 'amount',
            },
        ),
        migrations.CreateModel(
            name='AmountAdded',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.added')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.amount')),
            ],
            options={
                'db_table': 'ammount_added',
                'unique_together': {('added', 'amount')},
            },
        ),
        migrations.CreateModel(
            name='BaseOffer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'base_offer',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('amount_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.amountadded')),
                ('base_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baseoffer')),
            ],
            options={
                'db_table': 'offer',
                'unique_together': {('base_offer', 'amount_added')},
            },
        ),
        migrations.AddField(
            model_name='baseoffer',
            name='amount_added',
            field=models.ManyToManyField(through='api.Offer', to='api.amountadded'),
        ),
        migrations.AddField(
            model_name='added',
            name='amount',
            field=models.ManyToManyField(through='api.AmountAdded', to='api.amount'),
        ),
    ]
