# Generated by Django 4.0.5 on 2022-06-24 01:38

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Added',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'added',
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('amount', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=30)),
            ],
            options={
                'db_table': 'amount',
            },
        ),
        migrations.CreateModel(
            name='BaseOffer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'base_offer',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), api.models.validate_int])),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('addeds', models.ManyToManyField(to='api.added')),
                ('base_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baseoffer')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('state_order', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], max_length=30)),
            ],
            options={
                'db_table': 'order_list',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offer')),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
            options={
                'db_table': 'order',
                'unique_together': {('client', 'offer')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(through='api.Order', to='api.offer'),
        ),
        migrations.AddField(
            model_name='added',
            name='amount',
            field=models.ManyToManyField(to='api.amount'),
        ),
    ]
