# Generated by Django 4.0.5 on 2022-06-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseoffer',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
