# Generated by Django 4.0.5 on 2022-06-23 01:25

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11), api.models.validate_int])),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('state_order', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], max_length=30)),
            ],
            options={
                'db_table': 'order_list',
            },
        ),
        migrations.RenameField(
            model_name='baseoffer',
            old_name='amount_added',
            new_name='offers',
        ),
        migrations.AlterModelTable(
            name='amountadded',
            table='amount_added',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.offer')),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.orderlist')),
            ],
            options={
                'db_table': 'order',
                'unique_together': {('client', 'offer')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(through='api.Order', to='api.offer'),
        ),
    ]
