# Generated by Django 4.0.5 on 2022-06-24 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='added',
            old_name='amount',
            new_name='amounts',
        ),
    ]
