# Generated by Django 4.0.5 on 2022-06-26 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='offer',
            new_name='requested_offer',
        ),
    ]
