# Generated by Django 4.0.3 on 2022-05-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseofferorm',
            old_name='nombre',
            new_name='name',
        ),
    ]
