# Generated by Django 4.0.5 on 2022-06-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_offer_order_requested_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='address',
        ),
    ]
