# Generated by Django 4.0.5 on 2022-06-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_baseoffer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseoffer',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
