# Generated by Django 4.0.3 on 2022-05-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_nombre_baseofferorm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseofferorm',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='baseofferorm',
            table='base_offer',
        ),
    ]
