# Generated by Django 4.0.5 on 2022-06-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_client_orderlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
