# Generated by Django 4.0.5 on 2022-06-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_added_id_alter_baseoffer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='state_order',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Canceled', 'Canceled')], default='Pending', max_length=30),
        ),
    ]
