# Generated by Django 4.0.5 on 2022-06-24 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_amount_added_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='added',
            name='amounts',
        ),
        migrations.DeleteModel(
            name='Amount',
        ),
    ]
