# Generated by Django 4.0.3 on 2022-05-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_baseofferorm_id_alter_baseofferorm_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Added',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'added',
            },
        ),
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('amount', models.CharField(choices=[('LowMediumHigh', 'Lowmediumhigh')], max_length=30)),
            ],
            options={
                'db_table': 'amount',
            },
        ),
        migrations.CreateModel(
            name='AmountAdded',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.added')),
                ('amount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.amount')),
            ],
            options={
                'db_table': 'ammount_added',
            },
        ),
        migrations.CreateModel(
            name='BaseOffer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('base_price', models.PositiveSmallIntegerField()),
                ('amount_added', models.ManyToManyField(to='api.amountadded')),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.DeleteModel(
            name='BaseOfferORM',
        ),
        migrations.AddField(
            model_name='added',
            name='amount',
            field=models.ManyToManyField(through='api.AmountAdded', to='api.amount'),
        ),
    ]
