# Generated by Django 4.0.5 on 2022-06-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderlist_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='added',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amountadded',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='baseoffer',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
