# Generated by Django 4.0.5 on 2022-06-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_added_amounts_delete_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseoffer',
            name='addeds',
            field=models.ManyToManyField(to='api.added'),
        ),
    ]
