# Generated by Django 4.0.5 on 2022-06-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_baseoffer_addeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='added',
            name='price',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseoffer',
            name='price',
            field=models.PositiveSmallIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestedOffer',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('addeds', models.ManyToManyField(to='api.added')),
                ('base_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.baseoffer')),
            ],
            options={
                'db_table': 'requested_offer',
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='orders',
            field=models.ManyToManyField(through='api.Order', to='api.requestedoffer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.requestedoffer'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
