# Generated by Django 4.0.3 on 2022-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_amount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseoffer',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
